# Generated by Django 3.2.12 on 2023-03-07 16:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impression_total', models.IntegerField()),
                ('auction_type', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('mode', models.CharField(choices=[('fr', 'free'), ('sc', 'script')], max_length=2)),
                ('budget', models.IntegerField()),
                ('impression_revenue', models.IntegerField()),
                ('click_revenue', models.IntegerField()),
                ('conversion_revenue', models.IntegerField()),
                ('frequency_capping', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.category')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('image_url', models.TextField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.category')),
            ],
        ),
    ]
